[package]
name = "mymc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
azalea = "0.14.0"
tokio = { version = "1.48.0", features = ["full"] }
trace = "0.1.7"
tracing-subscriber = "0.3.20"
