[package]
name = "afkbot"
version = "0.1.0"
edition = "2024"

[dependencies]
azalea = { git = "https://github.com/azalea-rs/azalea", version = "0.14.0" }
tokio = { version = "1.48.0", features = ["full"] }
