[package]
name = "afkbot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
azalea = { git = "https://github.com/azalea-rs/azalea", version = "0.14.0+mc1.21.10" }
parking_lot = "0.12.5"
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }
uuid = "1.19.0"
