[package]
name = "ep"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
regex = "1.12.2"
reqwest = { version = "0.12.24", features = ["multipart", "stream"] }
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
